# Generated by Django 3.2.9 on 2023-07-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_leavemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavemodel',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leavemodel',
            name='half_day',
            field=models.BooleanField(default=False),
        ),
    ]
